baseURL: "https://rmb.info.np"
languageCode: "en-us"
title: "Rabindra's Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://blog.rmb.info.np
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: ""
  description: A portfolio for me
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Initialrise" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rabindra."
    subtitle: "I like to build and break things"
    content: "I am an enthusiastic web application developer who makes use of modern web technologies to build websites and has a knack for security stuffs"
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/initialrise
        - icon: fab fa-linkedin
          url: https://linkedin.com/rabindramb

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development, security and automation. I have a background in computer science, and I have a strong interest in the intersection of development and security.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"
        - "Python"
        - "FastAPI"

  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    items:

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Computer Science and Information Technolgy"
        school:
          name: "Asian School of Management and Technology"
          url: "https://asm.edu.np"
        date:
          "2019 - Ongoing"
          #GPA: "3.8 out of 5.0"
        content: |-
          Highlights
            - Completed coursework in data structures, algorithms, and other software engineering  and computer science principles.
            - Built different projects as required by the course syllabus of Bsc. CSIT
      - title: "High School"
        school:
          name: "Takshashila Academy"
          url: "https://tsa.edu.np"
        date:
          "2017 - 2019"
          #GPA: "3.9 out of 5.0"
        content: |-
          - I joined Science faculty and studied subjects like Physics, Chemistry, Biology, Mathematics

        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Asian Hackathon 2nd Runner up
        content: Secured 2nd runner up position by developing a web app that uses Object Detection to detect objects infront
        url: https://asm.edu.np
        image: /images/achievements/hackathon.jpg
      - title: Acknowledgement By Nokia
        content: Responsible disclosure of security vulnerabilities to Nokia.
        url: https://www.nokia.com/notices/responsible-disclosure/
        image: /images/achievements/nokia.jpeg
      - title: Acknowledgement By SIDN
        content: Responsibly disclosed security vulnerability to SIDN.
        url: https://www.sidn.nl/
        image: /images/achievements/sidn.jpeg
      - title: Acknowledgement By BASF
        content: Landed myself in Heroes of BASF by responsibly disclosing security vulnerability to BASF
        url: https://www.basf.com/global/en/legal/responsible-disclosure-statement.html
      - title: Acknowledgement By US DOD
        content: Reported security vulnerabilites to US Department of Defense VDP.
        url: https://hackerone.com/rmb

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: StreamSurf
        content: A web application that allows you to stream your screen directly  to Youtube from the browser.
        image: /images/projects/streamsurf.jpg
        featured:
          name: Demo
          link: #
        badges:
          - "NodeJS"
          - "Express"
          - "FFMPEG"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/StreamSurf

      - title: BrahmaShikshya
        content: An e-learning and e-commerce website that allows students to purchase and view video courses.
        image: /images/projects/brahmashiksya.png
        featured:
          name: Demo
          link: #
        badges:
          - "PHP"
          - "Esewa Integration"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/brahmashikshya

      - title: Canteen Ordering System
        content: A clean and simple food ordering web application that allows you to select and purchase food
        image: /images/projects/cosv2.png
        featured:
          name: Demo
          link: #
        badges:
          - "React"
          - "NodeJS"
          - "Express"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/cos

      - title: Project ThirdVision
        content: A web app that uses YOLOV3 algorithm to detect objects via the camera and uses text to speech to dictate it.
        image: /images/projects/od.jpg
        featured:
          name: Demo
          link: #
        badges:
          - "Flask"
          - "YOLOV3"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/AsianHack2022

      - title: WeConnect
        content: A clean and simple reddit like forum to connect students with common faculties
        image: /images/projects/weconnect.jpg
        featured:
          name: Demo
          link: #
        badges:
          - "C#"
          - "DOTNET"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/WeConnect

      - title: Aparichit
        content: A website promoting transparency and citizen participation in Kathmandu. It facilitates reporting corruption, accessing emergency services, sharing suggestions, and seeking assistance anonymously.
        image: /images/projects/aparichit.png
        featured:
          name: Demo
          link: #
        badges:
          - "PHP"
        links:
          - icon: fab fa-github
            url: https://github.com/initialrise/aparichit

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to drop me a mail!
    btnName: Mail me
    btnLink: mailto:queries@rmb.info.np
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/initialrise
      linkedin: https://linkedin.com/rabindramb
      twitter: https://twitter.com/initialrise
      instagram: https://instagram.com/rabindramb
      #facebook: https://facebook.com/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
